#[derive(Clone, sqlx::FromRow)]
pub struct ServiceOrderRow {
    pub id: i64,
    pub user_id: i64,
    pub order_no: String,
    pub service_item_id: i64,
    pub service_item_name: String,
    pub region_code: String,
    pub region_name: String,
    pub city_name: String,
    pub district_name: String,
    pub address_id: i64,
    pub service_address: String,
    pub contact_name: String,
    pub contact_phone: String,
    pub service_date: String,
    pub service_time_slot: String,
    pub note: String,
    pub status: String,
    pub assigned_veteran_id: Option<i64>,
    pub assigned_veteran_name: Option<String>,
    pub assigned_veteran_phone: Option<String>,
    pub dispatch_message: String,
    pub created_at: String,
}
